services:
  frontend:
    build: { context: ., dockerfile: Dockerfile.dev }
    env_file: [.env.local]
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports: ["3000:3000"]
volumes:
  node_modules:
